name: CMake on multiple platforms

on:
  push:
    branches: [ "master" ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            artifact_name: windows-x64-msvc
            c_compiler: cl
            cpp_compiler: cl
          - os: ubuntu-latest
            artifact_name: linux-x64-gcc
            c_compiler: gcc
            cpp_compiler: g++
          - os: ubuntu-latest
            artifact_name: linux-x64-clang
            c_compiler: clang
            cpp_compiler: clang++
          - os: macos-latest
            artifact_name: macos-arm64-clang
            c_compiler: clang
            cpp_compiler: clang++
          - os: macos-13
            artifact_name: macos-x64-clang
            c_compiler: clang
            cpp_compiler: clang++

    steps:
      - uses: actions/checkout@v4

      - name: Configure
        run: |
          cmake -B build \
            -DCMAKE_C_COMPILER=${{ matrix.c_compiler }} \
            -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }} \
            -DCMAKE_BUILD_TYPE=Release \
            -S .

      - name: Build
        run: cmake --build build --config Release

      - name: Test
        working-directory: build
        run: ctest --build-config Release

      - name: Package
        run: |
          mkdir -p package
          echo "Looking for binaries to package..."

          if [[ "$RUNNER_OS" == "Windows" ]]; then
            find build -name "*.exe" -exec cp {} package/ \;
            find build -name "*.dll" -exec cp {} package/ \;
            7z a ${{ matrix.artifact_name }}.zip ./package/*
          else
            find build -type f -perm +111 ! -name "*.a" ! -name "*.so*" ! -name "*.dylib*" | while read -r f; do
              file "$f" | grep -qE "Mach-O|ELF|executable" && cp "$f" package/
            done
            tar -czf ${{ matrix.artifact_name }}.tar.gz -C package .
          fi

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: |
            ${{ matrix.artifact_name }}.zip
            ${{ matrix.artifact_name }}.tar.gz
          if-no-files-found: ignore
          retention-days: 30

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ github.ref_name }} \
            --title "Release ${{ github.ref_name }}" \
            --generate-notes \
            --repo ${{ github.repository }}

      - name: Upload Release Artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          for file in artifacts/*/*; do
            echo "Uploading $file"
            gh release upload ${{ github.ref_name }} "$file" --repo ${{ github.repository }}
          done