name: Build and Release CMake Project

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types: [published]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v1

      - name: Create build directory
        run: cmake -E make_directory build

      - name: Configure with CMake
        working-directory: build
        run: cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS_RELEASE="-Os -s" -DCMAKE_EXE_LINKER_FLAGS="-s"

      - name: Build
        working-directory: build
        run: cmake --build . --config Release

      - name: Package Artifacts
        if: github.event_name == 'release'
        run: |
          cd build
          if [ "${{ runner.os }}" == "Windows" ]; then
            7z a ../${{ runner.os }}-build.zip *
          elif [ "${{ runner.os }}" == "macOS" ]; then
            tar -czf ../${{ runner.os }}-build.tar.gz *
          else
            tar -czf ../${{ runner.os }}-build.tar.gz *
          fi
        shell: bash

      - name: Upload Release Artifact
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ runner.os }}-build.zip
            ${{ runner.os }}-build.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}